
LIB=	ssl
SHLIB_MAJOR=	56

NO_LINT=

.if exists(Makefile.man.libressl)
.include "Makefile.man.libressl"
.endif
.include "../libcrypto/Makefile.inc.libressl"

LSSL_SRC= ${LIBRESSL_SRC}/ssl

### This is copied straight from the original Makefile
### src/lib/libssl/ssl/Makefile
# $OpenBSD: Makefile,v 1.81 2023/11/22 15:55:28 tb Exp $

CFLAGS+= -Wall -Wundef
##LibreBSD: OpenBSD COMPILER_VERSION -> FreeBSD COMPILER_TYPE
.if ${COMPILER_TYPE:L} == "clang"
CFLAGS+= -Werror -Wshadow
.endif

CFLAGS+= -DLIBRESSL_INTERNAL
.ifdef NAMESPACE
CFLAGS+= -DLIBRESSL_NAMESPACE
.endif
.ifdef TLS1_3_DEBUG
CFLAGS+= -DTLS13_DEBUG
.endif
##LibreBSD: Replaced with paths from portable
CFLAGS+= -I${LSSL_SRC}
CFLAGS+= -I${LCRYPTO_SRC}/hidden
CFLAGS+= -I${LCRYPTO_SRC}/bio
CFLAGS+= -I${LSSL_SRC}/hidden

##LibreBSD: FreeBSD doesn't use LDADD
LIBADD=	crypto

##LibreBSD: TODO
##LibreBSD: VERSION_SCRIPT=	Symbols.map
##LibreBSD: SYMBOL_LIST=	${.CURDIR}/Symbols.list

SRCS= \
	bio_ssl.c \
	bs_ber.c \
	bs_cbb.c \
	bs_cbs.c \
	d1_both.c \
	d1_lib.c \
	d1_pkt.c \
	d1_srtp.c \
	pqueue.c \
	s3_cbc.c \
	s3_lib.c \
	ssl_asn1.c \
	ssl_both.c \
	ssl_cert.c \
	ssl_ciph.c \
	ssl_ciphers.c \
	ssl_clnt.c \
	ssl_err.c \
	ssl_init.c \
	ssl_kex.c \
	ssl_lib.c \
	ssl_methods.c \
	ssl_packet.c \
	ssl_pkt.c \
	ssl_rsa.c \
	ssl_seclevel.c \
	ssl_sess.c \
	ssl_sigalgs.c \
	ssl_srvr.c \
	ssl_stat.c \
	ssl_tlsext.c \
	ssl_transcript.c \
	ssl_txt.c \
	ssl_versions.c \
	t1_enc.c \
	t1_lib.c \
	tls12_key_schedule.c \
	tls12_lib.c \
	tls12_record_layer.c \
	tls13_client.c \
	tls13_error.c \
	tls13_handshake.c \
	tls13_handshake_msg.c \
	tls13_key_schedule.c \
	tls13_legacy.c \
	tls13_lib.c \
	tls13_quic.c \
	tls13_record.c \
	tls13_record_layer.c \
	tls13_server.c \
	tls_buffer.c \
	tls_content.c \
	tls_key_share.c \
	tls_lib.c


##LibreBSD: OpenBSD HDRS is FreeBSD INCS
INCS=	dtls1.h srtp.h ssl.h ssl2.h ssl23.h ssl3.h tls1.h
CFLAGS+=	-I${LIBRESSL_SRC}/include

.PATH:	${LSSL_SRC} \
	${LIBRESSL_SRC}/include/openssl \
	${LIBRESSL_SRC}/man

INCSDIR=${INCLUDEDIR}/openssl

.include <bsd.lib.mk>


